site_name: "Micronutrient Intervention Modeling Project"

nav:
  - Home: index.md
  - Overview:
    - The Tool: overview/tool.md
    - Key Messages: overview/key_messages.md
    - overview/policy_issues.md
    - overview/outreach.md
  - Countries of Interest:
    - Cameroon:
      - Background and Policy Issues: countries/cameroon/background.md
      - Cameroon Micronutrient Intervention Programs: countries/cameroon/programs.md
      - Models: countries/cameroon/models.md
      - countries/cameroon/policy_engagement.md
    - Ethiopia: 
      - countries/ethiopia/background.md
  - Publications: publications.md
  - Related Resources: related_resources.md 
  - About Us:
    - Directory: about/directory.md
    - Sources of Support: about/support.md
  - Events: 
    - MINIMOD Hosted Events: events/events.md
    - Related Events: events/related_events.md
    - Other Events: events/other_activities.md

theme:
  logo: pictures/ucdavis_logo_gold.png
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  custom_dir: overrides

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/colors.css
  - stylesheets/admon.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.css

copyright: Copyright &copy The Regents of the University of California, Davis campus. All rights reserved.

plugins:
  - git-revision-date-localized
  - search
  - macros
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"

extra:
  url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - attr_list
  - footnotes