site_name: "Micronutrient Intervention Modeling Project"

nav:
  - Home: index.md
  - Overview:
    - The Tool: overview/tool.md
    - Key Messages: overview/key_messages.md
    - overview/policy_issues.md
    - overview/outreach.md
  - Focus Countries:
    - World Map: countries/index.md
    - Burkina Faso: 
      - countries/burkina_faso/background.md
    - Cameroon:
      - Background and Policy Issues: countries/cameroon/background.md
      - Cameroon Micronutrient Intervention Programs: countries/cameroon/programs.md
      - countries/cameroon/policy_engagement.md
    - Ethiopia: 
      - countries/ethiopia/background.md
    - Ghana: 
      - countries/ghana/background.md
    - Haiti: 
      - countries/haiti/background.md
    - Malawi: 
      - countries/malawi/background.md
    - Nigeria: 
      - countries/Nigeria/background.md
    - Senegal: 
      - countries/senegal/background.md
  - MINIMOD Tools:
    - MINIMOD-Full Tool: 
      - MINIMOD: minimod_tools/minimod.md
      - Overview: minimod_tools/minimod/overview.md
      - Cost Models: minimod_tools/minimod/cost_models.md
      - Benefits Models: minimod_tools/minimod/benefits_models.md
      - Linking Benefits and Costs: minimod_tools/minimod/linking_benefits.md
      - Economic Optimization: minimod_tools/minimod/economic_optimization.md
    - MINIMOD-SD Tool: 
      - MINIMOD-SD: minimod_tools/minimod_sd.md
      - Overview: minimod_tools/minimod_sd/overview.md
      - Cost Models: minimod_tools/minimod_sd/cost_models.md
      - Benefits Models: minimod_tools/minimod_sd/benefits_models.md
      - Linking Benefits and Costs: minimod_tools/minimod/linking_benefits.md
      - Economic Optimization: minimod_tools/minimod_sd/economic_optimization.md
  - Publications: publications.md
  - Collaborations: collaborations.md
  - News: news.md
  - Related Resources: related_resources.md 
  - Events: 
    - MINIMOD Events: events/events.md
    - Research and Policy Engagement Events: events/research_events.md
    - Other Events: events/other_activities.md
  - Apps: apps.md
  - About Us:
    - Directory: about/directory.md
    - Sources of Support: about/support.md

theme:
  logo: pictures/ucdavis_logo_gold.png
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  custom_dir: overrides

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/colors.css
  - stylesheets/admon.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.css

copyright: Copyright &copy The Regents of the University of California, Davis campus. All rights reserved.

plugins:
  - git-revision-date-localized
  - search
  - macros
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"

extra:
  url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - attr_list
  - footnotes
