site_name: "Micronutrient Intervention Modeling Project"

nav:
  - Home: index.md
  - Overview:
    - The MINIMOD Tool Framework: overview/tool.md
    - Key Messages: overview/key_messages.md
    - overview/policy_issues.md
    - Collaboration, Training, and Policy Engagement: overview/outreach.md
  - Focus Countries:
    - World Map: countries/index.md
    - Burkina Faso:
      - Background and Policy Issues: countries/burkina_faso/background.md
      - Micronutrient Intervention Programs: countries/burkina_faso/programs.md
      - Tool Development: countries/burkina_faso/tool_development.md
      - Policy Engagement: countries/burkina_faso/policy.md
      - Collaborating Organizations: countries/burkina_faso/collaborations.md
    - Cameroon:
      - Background and Policy Issues: countries/cameroon/background.md
      - Micronutrient Intervention Programs: countries/cameroon/programs.md
      - Tool Development: countries/cameroon/tool_development.md
      - Policy Engagement: countries/cameroon/policy_engagement.md
    - Ethiopia:
      - Background: countries/ethiopia/background.md
      - Micronutrient Intervention Programs: countries/ethiopia/programs.md
    - Ghana:
      - Background: countries/ghana/background.md
      - Micronutrient Intervention Programs: countries/ghana/programs.md
    - Haiti:
      - Background: countries/haiti/background.md
      - Micronutrient Intervention Programs: countries/haiti/programs.md
    - Malawi:
      - Background: countries/malawi/background.md
      - Micronutrient Intervention Programs: countries/malawi/programs.md
    - Nigeria:
      - Background and Policy Issues: countries/nigeria/background.md
      - Micronutrient Intervention Programs: countries/nigeria/programs.md
      - Tool Development: countries/nigeria/tool_development.md
      - Policy Engagement: countries/nigeria/policy.md
      - Collaborating Organizations: countries/nigeria/collaborations.md
    - Senegal:
      - Background and Policy Issues: countries/senegal/background.md
      - Micronutrient Intervention Programs: countries/senegal/programs.md
      - Tool Development: countries/senegal/tool_development.md
      - Policy Engagement: countries/senegal/policy.md
      - Collaborating Organizations: countries/senegal/collaborations.md
  - MINIMOD Models:
    - MINIMOD Models - An Overview: minimod_models/minimod_models_overview/models_overview_text.md
    - MINIMOD Nutritional Needs and Intervention Program Benefits:
      - MINIMOD-Full: minimod_models/minimod_models_overview/minimod_full_text.md
      - MINIMOD-SD (Secondary Data): minimod_models/minimod_sd/minimod_sd_text.md
    - MINIMOD - Lives Saved Tool (LiST) Model: minimod_models/minimod_list/minimod_list.md
    - MINIMOD Intervention Program Cost Models: minimod_models/minimod_intervention/minimod_intervention_text.md
    - Linking MINIMOD Intervention Program Benefits and Costs: minimod_models/minimod_linking/minimod_linking_text.md
    - MINIMOD Economic Optimization Model: minimod_models/minimod_optimization/minimod_optimization_text.md
  - Publications: publications.md
  - Collaborations: collaborations.md
  - Related Resources: related_resources.md
  - Apps: apps.md
  - About Us:
    - Directory: about/directory.md
    - Sources of Support: about/support.md

theme:
  logo: pictures/ucdavis_logo_gold.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  custom_dir: overrides

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.js

extra_css:
  - stylesheets/colors.css
  - stylesheets/admon.css
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css
  - stylesheets/carousel.css

copyright: Copyright &copy The Regents of the University of California, Davis campus. All rights reserved.

plugins:
  - git-revision-date-localized
  - search
  - table-reader
  - macros
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"

extra:
  url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - attr_list
  - footnotes
