site_name: "Micronutrient Intervention Modeling Project"

nav:
  - Home: index.md
  - Overview:
    - The Tool: overview/tool.md
    - Key Messages: overview/key_messages.md
  - Countries of Interest:
    - Cameroon:
      - Background and Policy Issues: countries/cameroon/background.md

theme:
  logo: pictures/ucdavis_logo_gold.png
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  custom_dir: overrides

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/colors.css
  - stylesheets/admon.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.1.0/mdb.min.css

copyright: Copyright &copy The Regents of the University of California, Davis campus. All rights reserved.

plugins:
  - git-revision-date-localized

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - attr_list