name: mkdocs-deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install wheel mkdocs-material mkdocs mkdocs-git-revision-date-localized-plugin mkdocs-bibtex mkdocs-macros-plugin mkdocs-table-reader-plugin openpyxl
      - run: mkdocs gh-deploy --force
